name: LOCI Analysis
on:
  push:
    branches:
      - main*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  loci:
    runs-on: ubuntu-latest

    env:
      LOCI_PROJECT: "nextest"
      LOCI_API_KEY: '${{ secrets.LOCI_API_KEY }}'
      LOCI_BACKEND_URL: '${{ vars.LOCI_BACKEND_URL }}'

    environment: ${{ vars.LOCI_ENV || 'PROD__AL_DEMO' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt install gcc-aarch64-linux-gnu && rustup target add aarch64-unknown-linux-gnu
        shell: bash -euo pipefail {0}

      - name: Build
        run: RUSTFLAGS="-C debuginfo=2" cargo build --target aarch64-unknown-linux-gnu --release
        shell: bash -euo pipefail {0}

      - name: Upload
        uses: auroralabs-loci/loci-action@v1
        with:
          mode: upload
          binaries: |
                target/aarch64-unknown-linux-gnu/release/build-seed-archive
                target/aarch64-unknown-linux-gnu/release/cargo-nextest
                target/aarch64-unknown-linux-gnu/release/fake-interceptor
                target/aarch64-unknown-linux-gnu/release/grab-foreground
                target/aarch64-unknown-linux-gnu/release/internal-test
                target/aarch64-unknown-linux-gnu/release/large-alloc
                target/aarch64-unknown-linux-gnu/release/passthrough
                target/aarch64-unknown-linux-gnu/release/rustc-shim
                target/aarch64-unknown-linux-gnu/release/zstd-dict
          project: '${{ env.LOCI_PROJECT }}'
